version: '3'
services:
  front:
    build: .
    platform: linux/amd64
    volumes:
      - .:/grow
      - node_modules:/grow/node_modules
    command: sh -c "yarn start"
    ports:
     - "3001:3000"
    tty: true

volumes:
  node_modules: