# Test
name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - name: Get Workflow Runs
      id: get_runs
      run: |
        echo "::set-output name=runs::$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=queued" | jq -r '.workflow_runs[].id')"

    - name: Cancel Workflow Runs
      if: steps.get_runs.outputs.runs != ''
      run: |
        for run_id in $(echo "${{ steps.get_runs.outputs.runs }}"); do
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs/${run_id}/cancel"
        done
